### ISSUE TITLE
Instrument Harpsichord

### ISSUE THREAD

**Issue by g-omarsdottir** [Mickjitsu/team_6_hackathon#14]
Connected to Epic #4 

As a user, I want to be able to play the digital **harpsichord**, so that I can play the game.

## Acceptance Criteria

- Digital harpsichord
- Audio feedback
- Visual feedback 

## Requirements

- [x] Audio files for single notes
- [ ] Reuse piano notes with slight changes (retro color)
- [x] Reuse JavaScript to operate the harpsichord

**Comment by erinvdoyle** [comment]
The harpsichord instrument will need to be a future feature as due to deadline time, we focused on hitting the MVPs of our project rather than implementing this bonus feature
